tap "ksdme/tap"
tap "tonisives/tap"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Bourne-Again SHell, a UNIX command interpreter
brew "bash"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Resource monitor. C++ version and continuation of bashtop and bpytop
brew "btop"
# Manage your dotfiles across multiple diverse machines, securely
brew "chezmoi"
# Pack, ship and run any application as a lightweight container
brew "docker"
# Modern, maintained replacement for ls
brew "eza"
# Like neofetch, but much faster because written mostly in C
brew "fastfetch"
# Command-line fuzzy finder written in Go
brew "fzf"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Interact with Google Gemini AI models from the command-line
brew "gemini-cli"
# GitHub command-line tool
brew "gh"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Improved top (interactive process viewer)
brew "htop"
# Kubernetes command-line interface
brew "kubernetes-cli"
# Tool for linting and static analysis of Lua code
brew "luacheck"
# Run a Kubernetes cluster locally
brew "minikube"
# MongoDB Shell to connect, configure, query, and work with your MongoDB database
brew "mongosh"
# Open source relational database management system
brew "mysql-client"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Extremely fast Python linter, written in Rust
brew "ruff"
# Cross-shell prompt for astronauts
brew "starship"
# Opinionated Lua code formatter
brew "stylua"
# Terminal multiplexer
brew "tmux"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Shell extension to navigate your filesystem faster
brew "zoxide"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# A utility toolkit of most commonly used tools by software developers and IT professionals
brew "ksdme/tap/ut"
# Menu bar tool to limit maximum charging percentage
cask "aldente"
# Application uninstaller
cask "appcleaner"
# Display management tool
cask "betterdisplay"
# OpenAI's official ChatGPT desktop app
cask "chatgpt"
# Write, edit, and chat about your code with AI
cask "cursor"
# Databases and SQL IDE
cask "datagrip"
# App to build and share containerised applications and microservices
cask "docker-desktop"
cask "font-jetbrains-mono-nerd-font"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Web browser
cask "google-chrome"
# Keyboard shortcuts for every button on your screen
cask "homerow"
# Tool for multi-language users
cask "input-source-pro"
# Keyboard customiser
cask "karabiner-elements"
# App to write, plan, collaborate, and get organised
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Control your tools with a few keystrokes
cask "raycast"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Screenshot measurement and annotation tool
cask "shottr"
# Team communication and collaboration software
cask "slack"
# GPU-accelerated cross-platform terminal emulator and multiplexer
cask "wezterm"
# Gecko based web browser
cask "zen"
vscode "anysphere.cursorpyright"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
